name: go-learn-mystifying_fermat
services:
  backend:
    build:
      context: C:\Users\MSI-Genyuan\Desktop\golang-learn\go-learn\backend
      dockerfile: Dockerfile
    command:
    - infinity
    depends_on:
      db:
        condition: service_started
    entrypoint:
    - sleep
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: go-learn-mystifying_fermat
    networks:
      default: null
    secrets:
    - source: db-password
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: C:\Users\MSI-Genyuan\Desktop\golang-learn\go-learn
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-go-learn-mystifying_fermat-backend
      target: /home/vscode
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
    - "3306"
    image: mariadb
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: go-learn-mystifying_fermat
    networks:
      default: null
    restart: always
    secrets:
    - source: db-password
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  proxy:
    build:
      context: C:\Users\MSI-Genyuan\Desktop\golang-learn\go-learn\proxy
      dockerfile: Dockerfile
    command:
    - infinity
    depends_on:
      backend:
        condition: service_started
    entrypoint:
    - sleep
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: go-learn-mystifying_fermat
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "8080"
      protocol: tcp
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: C:\Users\MSI-Genyuan\Desktop\golang-learn\go-learn
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-go-learn-mystifying_fermat-proxy
      target: /home/vscode
networks:
  default:
    name: go-learn-mystifying_fermat_default
volumes:
  db-data:
    name: go-learn-mystifying_fermat_db-data
  vsCodeServerVolume-go-learn-mystifying_fermat-backend:
    name: vsCodeServerVolume-go-learn-mystifying_fermat-backend
  vsCodeServerVolume-go-learn-mystifying_fermat-proxy:
    name: vsCodeServerVolume-go-learn-mystifying_fermat-proxy
secrets:
  db-password:
    name: go-learn-mystifying_fermat_db-password
    file: C:\Users\MSI-Genyuan\Desktop\golang-learn\go-learn\db\password.txt
